name: 'Powerful pull request comments'
description:
  'Easily create and update PR comments. Comments can be sticky, split into
  sections, and more...'
author: 'Julien P.'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  GITHUB_TOKEN:
    description: 'GITHUB TOKEN'
    required: true
  body:
    description: 'body'
    required: true
  sticky:
    description: 'Is the comment sticky?'
    default: 'false'
  commentId:
    description: 'Comment id to update'
    default: ''
  section:
    description: 'The section you want to update'
    default: ''

# Define your outputs here.
outputs:
  commentId:
    description: 'Comment id'

runs:
  using: node20
  main: dist/index.js
