name: 'Powerful pull request comment'
description:
  'Easily create and update PR comments. Comments can be sticky, split into
  sections, and more...'
author: 'Julien P.'

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: 'message-square'
  color: 'purple'

# Define your inputs here.
inputs:
  GITHUB_TOKEN:
    description: 'GITHUB TOKEN'
    required: true
  body:
    description: "The comment's body or the section's body"
    required: true
  sticky:
    description: 'Is the comment sticky?'
    default: 'false'
  commentId:
    description: "Comment's id to update"
    default: ''
  section:
    description: "The section's name to update"
    default: ''

# Define your outputs here.
outputs:
  commentId:
    description: "Comment's id"

runs:
  using: node20
  main: dist/index.js
