name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  GITHUB_TOKEN:
    description: 'GITHUB TOKEN'
    required: true
  body:
    description: 'body'
    required: true
  commentId:
    description: 'Comment id to update'
    default: ''

# Define your outputs here.
outputs:
  commentId:
    description: 'Comment id'

runs:
  using: node20
  main: dist/index.js
