name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Create standard comment
        id: test-action
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          body: |
            **This comment will be updated**

      - name: Display comment id
        run: echo "Hello :) ${{steps.test-action.outputs.commentId}}"

      - name: Sleep for 5s
        run: sleep 5s
        shell: bash

      - name: Update standard comment and add section
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          commentId: ${{steps.test-action.outputs.commentId}}
          body: |
            Hello from ci workflow
            Second line
            Third line
            **Text in bold**
            # My section
            <!-- POWERFUL PR SECTION START: firstSection -->
            This section will be updated...
            <!-- POWERFUL PR SECTION END: firstSection -->

      - name: Sleep for 5s
        run: sleep 5s
        shell: bash

      - name: Update section in a standard comment
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          commentId: ${{steps.test-action.outputs.commentId}}
          section: firstSection
          body: |
            Hi 👋
            ![Screenshot of a comment on a GitHub issue showing an image, added in the Markdown, of an Octocat smiling and raising a tentacle.](https://myoctocat.com/assets/images/base-octocat.svg)

      - name: Test sticky comment with sections
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          sticky: true
          body: |
            I'm a comment containing multiple sections.
            Each section can be updated separately.
            # Sections
            <!-- POWERFUL PR SECTION START: firstSection -->
            - first section: This content will be updated...
            <!-- POWERFUL PR SECTION END: firstSection -->
            <!-- POWERFUL PR SECTION START: secondSection -->
            - second section: This content will be updated...
            <!-- POWERFUL PR SECTION END: secondSection -->

      - name: Sleep for 5s
        run: sleep 5s
        shell: bash

      - name: Update sticky comment first section
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          section: firstSection
          sticky: true
          body: |
            - The content of the first section has been updated
            - **well done**

      - name: Sleep for 5s
        run: sleep 5s
        shell: bash

      - name: Update sticky comment second section
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          section: secondSection
          sticky: true
          body: |
            - The content of the second section has been updated
            - **Really nice 🤗**
